version: "3.7"

services:
  web:
    container_name: custom-layers-api
    build: ./src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8010
    volumes:
      - ./src/:/usr/src/app/
    environment:
      - DATABASE_URL=postgresql://postgres:secret@localhost:5436/custom_layers
      - CREDENTIALS_URL=http://localhost:8040/auth/credentials
    network_mode: host
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=custom_layers
    ports:
      - 5436:5432

volumes:
  postgres_data:
